// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using financial;

#nullable disable

namespace financial_app.Migrations
{
    [DbContext(typeof(FinancialContext))]
    partial class FinancialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("financial.finance_categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("_finance_categories");
                });

            modelBuilder.Entity("financial.finance_data", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("cost_fixed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("recipient1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("recipient2")
                        .HasColumnType("int");

                    b.Property<double>("value")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("_finance_data");
                });
#pragma warning restore 612, 618
        }
    }
}
